name: event_booking
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

# App packages

  get: ^4.6.5
  shared_preferences: ^2.0.8
  http: ^0.13.5
  animate_do: ^3.0.2
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.7.0
  loading_animation_widget: ^1.2.0+4
  flutter_html: ^3.0.0-alpha.6
  image_picker: ^0.8.7+2
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  flutter_staggered_grid_view: ^0.6.2
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^4.3.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  url_launcher: ^6.1.10
  flutter_typeahead: ^4.3.7
  geolocator: ^9.0.2

#  animations: ^2.0.7
#  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          style: italic
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
          style: italic


